// Mock data cho Sổ tay từ vựng
export interface VocabularyItem {
    id: string;
    word: string;
    pos: string; // Danh từ, Động từ, Tính từ, Trạng từ
    phonetic: string;
    meaning: string;
    hanja?: string[]; // Âm Hán Việt tương ứng
    example?: string;
    image?: string;
    isFavorite?: boolean;
    learnedCount?: number; // Số lần đã học
}

export interface VocabularyNotebook {
    id: string;
    name: string;
    description?: string;
    color?: string;
    totalWords: number;
    learnedWords: number;
    masteredWords: number;
    lastUpdated: string;
    createdDate: string;
    words: VocabularyItem[];
}

// Bộ từ vựng "Du lịch"
export const NOTEBOOK_TRAVEL: VocabularyNotebook = {
    id: 'travel-1',
    name: 'Du lịch',
    description: 'Từ vựng liên quan đến du lịch và chuyến đi',
    color: '#FF6B6B',
    totalWords: 16,
    learnedWords: 12,
    masteredWords: 8,
    lastUpdated: '2024-04-10',
    createdDate: '2024-03-15',
    words: [
        {
            id: 'travel-1',
            word: '호텔',
            pos: 'Danh từ',
            phonetic: '/ho tel/',
            meaning: 'Khách sạn',
            hanja: ['Khách', 'Sạn'],
            example: '호텔에 가다',
            isFavorite: true,
            learnedCount: 5,
        },
        {
            id: 'travel-2',
            word: '공항',
            pos: 'Danh từ',
            phonetic: '/gong hang/',
            meaning: 'Sân bay',
            hanja: ['Công', 'Hàng'],
            example: '공항에서 만나다',
            isFavorite: true,
            learnedCount: 3,
        },
        {
            id: 'travel-3',
            word: '표',
            pos: 'Danh từ',
            phonetic: '/pyo/',
            meaning: 'Vé',
            hanja: ['Phiếu'],
            example: '표를 사다',
            isFavorite: false,
            learnedCount: 2,
        },
        {
            id: 'travel-4',
            word: '짐',
            pos: 'Danh từ',
            phonetic: '/jim/',
            meaning: 'Hành lý',
            hanja: [],
            example: '짐이 무겁다',
            isFavorite: true,
            learnedCount: 4,
        },
        {
            id: 'travel-5',
            word: '카메라',
            pos: 'Danh từ',
            phonetic: '/ka me ra/',
            meaning: 'Máy ảnh',
            hanja: [],
            example: '카메라를 가지고 가다',
            isFavorite: false,
            learnedCount: 1,
        },
        {
            id: 'travel-6',
            word: '여권',
            pos: 'Danh từ',
            phonetic: '/yo gwon/',
            meaning: 'Hộ chiếu',
            hanja: ['Nữ', 'Quyền'],
            example: '여권을 잃어버리다',
            isFavorite: true,
            learnedCount: 2,
        },
    ],
};

// Bộ từ vựng "Nhà hàng"
export const NOTEBOOK_RESTAURANT: VocabularyNotebook = {
    id: 'restaurant-1',
    name: 'Nhà hàng & Ăn uống',
    description: 'Từ vựng về đồ ăn, thức uống và nhà hàng',
    color: '#FAC858',
    totalWords: 20,
    learnedWords: 15,
    masteredWords: 10,
    lastUpdated: '2024-04-09',
    createdDate: '2024-02-20',
    words: [
        {
            id: 'food-1',
            word: '물',
            pos: 'Danh từ',
            phonetic: '/mul/',
            meaning: 'Nước',
            hanja: ['Nước'],
            example: '물을 마시다',
            isFavorite: true,
            learnedCount: 6,
        },
        {
            id: 'food-2',
            word: '밥',
            pos: 'Danh từ',
            phonetic: '/bap/',
            meaning: 'Cơm',
            hanja: [],
            example: '밥을 먹다',
            isFavorite: true,
            learnedCount: 8,
        },
        {
            id: 'food-3',
            word: '비빔밥',
            pos: 'Danh từ',
            phonetic: '/bi bim bap/',
            meaning: 'Cơm trộn Hàn Quốc',
            hanja: [],
            example: '비빔밥을 주세요',
            isFavorite: false,
            learnedCount: 3,
        },
        {
            id: 'food-4',
            word: '김치',
            pos: 'Danh từ',
            phonetic: '/gim chi/',
            meaning: 'Dưa cải chua',
            hanja: [],
            example: '김치가 맛있어요',
            isFavorite: true,
            learnedCount: 5,
        },
        {
            id: 'food-5',
            word: '불고기',
            pos: 'Danh từ',
            phonetic: '/bul go gi/',
            meaning: 'Nướng thịt bò',
            hanja: [],
            example: '불고기를 먹고 싶어요',
            isFavorite: false,
            learnedCount: 2,
        },
        {
            id: 'food-6',
            word: '맛있다',
            pos: 'Tính từ',
            phonetic: '/ma shi tta/',
            meaning: 'Ngon',
            hanja: [],
            example: '이 음식 맛있어요',
            isFavorite: true,
            learnedCount: 7,
        },
    ],
};

// Bộ từ vựng "Trường học"
export const NOTEBOOK_SCHOOL: VocabularyNotebook = {
    id: 'school-1',
    name: 'Trường học',
    description: 'Từ vựng về giáo dục và trường học',
    color: '#5DADE2',
    totalWords: 18,
    learnedWords: 10,
    masteredWords: 6,
    lastUpdated: '2024-04-08',
    createdDate: '2024-03-01',
    words: [
        {
            id: 'school-1',
            word: '학생',
            pos: 'Danh từ',
            phonetic: '/hak sen/',
            meaning: 'Học sinh, Sinh viên',
            hanja: ['Học', 'Sinh'],
            example: '저는 학생입니다',
            isFavorite: true,
            learnedCount: 10,
        },
        {
            id: 'school-2',
            word: '선생님',
            pos: 'Danh từ',
            phonetic: '/sun sang nim/',
            meaning: 'Giáo viên',
            hanja: ['Tiên', 'Sinh'],
            example: '선생님께 물어봐요',
            isFavorite: true,
            learnedCount: 8,
        },
        {
            id: 'school-3',
            word: '책',
            pos: 'Danh từ',
            phonetic: '/chaek/',
            meaning: 'Sách',
            hanja: [],
            example: '책을 읽다',
            isFavorite: false,
            learnedCount: 6,
        },
        {
            id: 'school-4',
            word: '숙제',
            pos: 'Danh từ',
            phonetic: '/suk je/',
            meaning: 'Bài tập về nhà',
            hanja: ['Thục', 'Đề'],
            example: '숙제를 하다',
            isFavorite: true,
            learnedCount: 4,
        },
        {
            id: 'school-5',
            word: '시험',
            pos: 'Danh từ',
            phonetic: '/si heom/',
            meaning: 'Kỳ thi',
            hanja: ['Thi', 'Nghiệm'],
            example: '시험을 보다',
            isFavorite: false,
            learnedCount: 3,
        },
        {
            id: 'school-6',
            word: '공부하다',
            pos: 'Động từ',
            phonetic: '/gong bu ha da/',
            meaning: 'Học tập, Nghiên cứu',
            hanja: ['Công', 'Bộ'],
            example: '매일 공부해요',
            isFavorite: true,
            learnedCount: 5,
        },
    ],
};

// Bộ từ vựng "Gia đình"
export const NOTEBOOK_FAMILY: VocabularyNotebook = {
    id: 'family-1',
    name: 'Gia đình',
    description: 'Từ vựng về các thành viên gia đình',
    color: '#F39C12',
    totalWords: 14,
    learnedWords: 14,
    masteredWords: 12,
    lastUpdated: '2024-04-07',
    createdDate: '2024-01-10',
    words: [
        {
            id: 'family-1',
            word: '엄마',
            pos: 'Danh từ',
            phonetic: '/eom ma/',
            meaning: 'Mẹ',
            hanja: [],
            example: '엄마가 요리를 해요',
            isFavorite: true,
            learnedCount: 12,
        },
        {
            id: 'family-2',
            word: '아빠',
            pos: 'Danh từ',
            phonetic: '/a ppa/',
            meaning: 'Bố',
            hanja: [],
            example: '아빠는 회사에 가요',
            isFavorite: true,
            learnedCount: 11,
        },
        {
            id: 'family-3',
            word: '형',
            pos: 'Danh từ',
            phonetic: '/hyung/',
            meaning: 'Anh trai (của nam)',
            hanja: ['Hành'],
            example: '형이 도와줘요',
            isFavorite: true,
            learnedCount: 9,
        },
        {
            id: 'family-4',
            word: '누나',
            pos: 'Danh từ',
            phonetic: '/nu na/',
            meaning: 'Chị gái (của nam)',
            hanja: [],
            example: '누나는 대학교에 가요',
            isFavorite: true,
            learnedCount: 8,
        },
        {
            id: 'family-5',
            word: '할아버지',
            pos: 'Danh từ',
            phonetic: '/ha la beo ji/',
            meaning: 'Ông ngoại/Ông nội',
            hanja: ['Hạ', 'Lão', 'Bộ', 'Tử'],
            example: '할아버지는 착해요',
            isFavorite: true,
            learnedCount: 10,
        },
        {
            id: 'family-6',
            word: '할머니',
            pos: 'Danh từ',
            phonetic: '/hal meo ni/',
            meaning: 'Bà ngoại/Bà nội',
            hanja: ['Hạ', 'Mẫu', 'Nữ'],
            example: '할머니가 밥을 만들어요',
            isFavorite: true,
            learnedCount: 9,
        },
    ],
};

// Bộ từ vựng "Sức khỏe"
export const NOTEBOOK_HEALTH: VocabularyNotebook = {
    id: 'health-1',
    name: 'Sức khỏe',
    description: 'Từ vựng về sức khỏe, bệnh tật',
    color: '#27AE60',
    totalWords: 12,
    learnedWords: 7,
    masteredWords: 3,
    lastUpdated: '2024-04-06',
    createdDate: '2024-03-25',
    words: [
        {
            id: 'health-1',
            word: '병원',
            pos: 'Danh từ',
            phonetic: '/byung won/',
            meaning: 'Bệnh viện',
            hanja: ['Bệnh', 'Viện'],
            example: '병원에 가요',
            isFavorite: true,
            learnedCount: 4,
        },
        {
            id: 'health-2',
            word: '의사',
            pos: 'Danh từ',
            phonetic: '/ui sa/',
            meaning: 'Bác sĩ',
            hanja: ['Y', 'Sĩ'],
            example: '의사를 만나다',
            isFavorite: true,
            learnedCount: 3,
        },
        {
            id: 'health-3',
            word: '약',
            pos: 'Danh từ',
            phonetic: '/yak/',
            meaning: 'Thuốc',
            hanja: ['Dược'],
            example: '약을 먹다',
            isFavorite: false,
            learnedCount: 2,
        },
        {
            id: 'health-4',
            word: '감기',
            pos: 'Danh từ',
            phonetic: '/gam gi/',
            meaning: 'Cảm lạnh',
            hanja: ['Cảm', 'Khí'],
            example: '감기가 걸렸어요',
            isFavorite: true,
            learnedCount: 2,
        },
        {
            id: 'health-5',
            word: '아프다',
            pos: 'Động từ',
            phonetic: '/a peu da/',
            meaning: 'Bị đau, Bị ốm',
            hanja: [],
            example: '머리가 아파요',
            isFavorite: true,
            learnedCount: 5,
        },
    ],
};

// Bộ từ vựng "Thể thao"
export const NOTEBOOK_SPORTS: VocabularyNotebook = {
    id: 'sports-1',
    name: 'Thể thao',
    description: 'Từ vựng về các môn thể thao',
    color: '#8E44AD',
    totalWords: 15,
    learnedWords: 9,
    masteredWords: 5,
    lastUpdated: '2024-04-05',
    createdDate: '2024-02-15',
    words: [
        {
            id: 'sports-1',
            word: '축구',
            pos: 'Danh từ',
            phonetic: '/chuk gu/',
            meaning: 'Bóng đá',
            hanja: ['Trục', 'Cầu'],
            example: '축구를 하다',
            isFavorite: true,
            learnedCount: 6,
        },
        {
            id: 'sports-2',
            word: '배구',
            pos: 'Danh từ',
            phonetic: '/bae gu/',
            meaning: 'Bóng chuyền',
            hanja: ['Bàn', 'Cầu'],
            example: '배구 경기를 보다',
            isFavorite: false,
            learnedCount: 2,
        },
        {
            id: 'sports-3',
            word: '수영',
            pos: 'Danh từ',
            phonetic: '/su yeong/',
            meaning: 'Bơi lội',
            hanja: ['Thủy', 'Anh'],
            example: '수영을 배우다',
            isFavorite: true,
            learnedCount: 4,
        },
        {
            id: 'sports-4',
            word: '운동',
            pos: 'Danh từ',
            phonetic: '/un dong/',
            meaning: 'Tập thể dục',
            hanja: ['Vận', 'Động'],
            example: '매일 운동해요',
            isFavorite: true,
            learnedCount: 7,
        },
        {
            id: 'sports-5',
            word: '이기다',
            pos: 'Động từ',
            phonetic: '/i gi da/',
            meaning: 'Thắng',
            hanja: [],
            example: '우리가 이겼어요',
            isFavorite: false,
            learnedCount: 3,
        },
    ],
};

// Danh sách tất cả các notebook
export const ALL_NOTEBOOKS: VocabularyNotebook[] = [
    NOTEBOOK_TRAVEL,
    NOTEBOOK_RESTAURANT,
    NOTEBOOK_SCHOOL,
    NOTEBOOK_FAMILY,
    NOTEBOOK_HEALTH,
    NOTEBOOK_SPORTS,
];

// Statistics
export const VOCABULARY_STATISTICS = {
    totalNotebooks: ALL_NOTEBOOKS.length,
    totalWords: ALL_NOTEBOOKS.reduce((sum, nb) => sum + nb.totalWords, 0),
    totalLearned: ALL_NOTEBOOKS.reduce((sum, nb) => sum + nb.learnedWords, 0),
    totalMastered: ALL_NOTEBOOKS.reduce((sum, nb) => sum + nb.masteredWords, 0),
    learningStreak: 7, // 7 ngày liên tiếp
    lastLearningDate: '2024-04-10',
};
